syntax = "proto3";

package illbuy.users.v1;

enum Errors {
    Unknown = 0;
    InvalidCredentials = 1;
    TokenExpired = 2;
    UserAlreadyExist = 3;
    ConstraintFailed = 4;
}

// @gleam record
message TokenMessage {
  string access_token = 1;
  string refresh_token = 2;
  int64 refresh_after = 3;
}

// @gleam record
message AuthenticateRequest {
  string username = 1;
  string password = 2;
}

// @gleam record
message AuthenticateResponse {
  oneof result {
    TokenMessage token = 1;
    Errors error = 2;
  }
}

// @gleam record
message RefreshTokenRequest {
  string refresh_token = 1; 
}

// @gleam record
message RefreshTokenResponse {
  oneof result {
    TokenMessage token = 1;
    Errors error = 2;
  }
}

// @gleam record
message RegisterUserRequest {
  string email = 1;
  string password = 2;
}

// @gleam record
message RegisterUserResponse {
  oneof result {
    TokenMessage token = 1;
    Errors error = 2; 
  }
}

service Users {
  rpc Authenticate(AuthenticateRequest) returns (AuthenticateResponse);
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse);
  rpc RegisterUser(RegisterUserRequest) returns (RegisterUserResponse);
}
