syntax = "proto3";

import "google/protobuf/empty.proto";

package illbuy.workspaces.pb;

message FullWorkspaceProps {
  int64 id = 1;
  string name = 2;
  repeated string emails = 3;
}

message WorkspaceProps {
  int64 id = 1;
  string name = 2;
} 

message WorkspaceList {
  repeated WorkspaceProps workspaces = 1;
}

message NewWorkspace {
  string name = 1;
}

message ChangeWorkspaceUser {
  int64 id = 1;
  string email = 2;
}

service WorkspaceService {
  rpc GetMyWorkspaces(google.protobuf.Empty) returns (WorkspaceList);
  rpc CreateNewWorkspace(NewWorkspace) returns (FullWorkspaceProps);
  rpc GetWorkspaceProps(WorkspaceProps) returns (FullWorkspaceProps);
  rpc InviteUser(ChangeWorkspaceUser) returns (FullWorkspaceProps);
  rpc RemoveUser(ChangeWorkspaceUser) returns (FullWorkspaceProps);
}
