repos:
  - repo: local
    hooks:
      - id: bun-format-frontend
        name: bun format frontend
        entry: cd frontend && bun run format
        language: system
        types: [file]
        pass_filenames: false
        files: ^frontend/
      - id: mix-format-backend
        name: mix format backend
        entry: cd backend && mix format
        language: system
        types: [elixir]
        pass_filenames: false
        files: ^backend/.*\.(ex|exs)$