repos:
  - repo: local
    hooks:
      - id: gleam-format
        name: format Gleam
        entry: gleam format
        language: system
        types: [gleam]
        pass_filenames: false
        files: ^.*\.(gleam)$