name = "illbuy"
version = "1.0.0"

description = "Open source tool for creating lists"
licences = ["MIT"]
repository = { type = "github", user = "turleo", repo = "illbuy" }
links = [{ title = "GitHub Wiki", href = "https://github.com/turleo/illbuy/wiki/" }]

[dependencies]
illbuy_shared = { path = "../shared" }
gleam_stdlib = ">= 0.44.0 and < 0.59.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
mist = ">= 4.0.7 and < 5.0.0"
logging = ">= 1.3.0 and < 2.0.0"
pog = ">= 3.2.0 and < 4.0.0"
argus = ">= 1.0.2 and < 2.0.0"
gwt = ">= 2.0.0 and < 3.0.0"
gleam_time = ">= 1.2.0 and < 2.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_otp = ">= 0.16.1 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
