syntax = "proto3";

package illbuy.users.pb;

enum Errors {
  WrongPassword = 0;
  WrongToken = 1;
  ConstrainFailed = 2;
}

message UserRequest {
  string email = 1;
  string password = 2;
}

message RefreshTokenRequest {
  string refreshToken = 1;
}

message TokenResponse {
  optional string accessToken = 1;
  optional string refreshToken = 2;
  optional Errors error = 3;
}

service UserService {
  rpc Login(UserRequest) returns (TokenResponse);
  rpc RefreshToken(RefreshTokenRequest) returns (TokenResponse);
}

