// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `users/user.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:illbuy.users.pb.UserRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct UserRequest {
    // message fields
    // @@protoc_insertion_point(field:illbuy.users.pb.UserRequest.email)
    pub email: ::std::string::String,
    // @@protoc_insertion_point(field:illbuy.users.pb.UserRequest.password)
    pub password: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:illbuy.users.pb.UserRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a UserRequest {
    fn default() -> &'a UserRequest {
        <UserRequest as ::protobuf::Message>::default_instance()
    }
}

impl UserRequest {
    pub fn new() -> UserRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "email",
            |m: &UserRequest| { &m.email },
            |m: &mut UserRequest| { &mut m.email },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "password",
            |m: &UserRequest| { &m.password },
            |m: &mut UserRequest| { &mut m.password },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<UserRequest>(
            "UserRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for UserRequest {
    const NAME: &'static str = "UserRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.email = is.read_string()?;
                },
                18 => {
                    self.password = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.email.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.email);
        }
        if !self.password.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.password);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.email.is_empty() {
            os.write_string(1, &self.email)?;
        }
        if !self.password.is_empty() {
            os.write_string(2, &self.password)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> UserRequest {
        UserRequest::new()
    }

    fn clear(&mut self) {
        self.email.clear();
        self.password.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static UserRequest {
        static instance: UserRequest = UserRequest {
            email: ::std::string::String::new(),
            password: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for UserRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("UserRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for UserRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for UserRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:illbuy.users.pb.RefreshTokenRequest)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RefreshTokenRequest {
    // message fields
    // @@protoc_insertion_point(field:illbuy.users.pb.RefreshTokenRequest.refreshToken)
    pub refreshToken: ::std::string::String,
    // special fields
    // @@protoc_insertion_point(special_field:illbuy.users.pb.RefreshTokenRequest.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RefreshTokenRequest {
    fn default() -> &'a RefreshTokenRequest {
        <RefreshTokenRequest as ::protobuf::Message>::default_instance()
    }
}

impl RefreshTokenRequest {
    pub fn new() -> RefreshTokenRequest {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "refreshToken",
            |m: &RefreshTokenRequest| { &m.refreshToken },
            |m: &mut RefreshTokenRequest| { &mut m.refreshToken },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RefreshTokenRequest>(
            "RefreshTokenRequest",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RefreshTokenRequest {
    const NAME: &'static str = "RefreshTokenRequest";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.refreshToken = is.read_string()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.refreshToken.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.refreshToken);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.refreshToken.is_empty() {
            os.write_string(1, &self.refreshToken)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RefreshTokenRequest {
        RefreshTokenRequest::new()
    }

    fn clear(&mut self) {
        self.refreshToken.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RefreshTokenRequest {
        static instance: RefreshTokenRequest = RefreshTokenRequest {
            refreshToken: ::std::string::String::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RefreshTokenRequest {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RefreshTokenRequest").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RefreshTokenRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RefreshTokenRequest {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:illbuy.users.pb.TokenResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TokenResponse {
    // message fields
    // @@protoc_insertion_point(field:illbuy.users.pb.TokenResponse.accessToken)
    pub accessToken: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:illbuy.users.pb.TokenResponse.refreshToken)
    pub refreshToken: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:illbuy.users.pb.TokenResponse.error)
    pub error: ::std::option::Option<::protobuf::EnumOrUnknown<Errors>>,
    // special fields
    // @@protoc_insertion_point(special_field:illbuy.users.pb.TokenResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TokenResponse {
    fn default() -> &'a TokenResponse {
        <TokenResponse as ::protobuf::Message>::default_instance()
    }
}

impl TokenResponse {
    pub fn new() -> TokenResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(3);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "accessToken",
            |m: &TokenResponse| { &m.accessToken },
            |m: &mut TokenResponse| { &mut m.accessToken },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "refreshToken",
            |m: &TokenResponse| { &m.refreshToken },
            |m: &mut TokenResponse| { &mut m.refreshToken },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "error",
            |m: &TokenResponse| { &m.error },
            |m: &mut TokenResponse| { &mut m.error },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TokenResponse>(
            "TokenResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TokenResponse {
    const NAME: &'static str = "TokenResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.accessToken = ::std::option::Option::Some(is.read_string()?);
                },
                18 => {
                    self.refreshToken = ::std::option::Option::Some(is.read_string()?);
                },
                24 => {
                    self.error = ::std::option::Option::Some(is.read_enum_or_unknown()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let Some(v) = self.accessToken.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(v) = self.refreshToken.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        if let Some(v) = self.error {
            my_size += ::protobuf::rt::int32_size(3, v.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let Some(v) = self.accessToken.as_ref() {
            os.write_string(1, v)?;
        }
        if let Some(v) = self.refreshToken.as_ref() {
            os.write_string(2, v)?;
        }
        if let Some(v) = self.error {
            os.write_enum(3, ::protobuf::EnumOrUnknown::value(&v))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TokenResponse {
        TokenResponse::new()
    }

    fn clear(&mut self) {
        self.accessToken = ::std::option::Option::None;
        self.refreshToken = ::std::option::Option::None;
        self.error = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TokenResponse {
        static instance: TokenResponse = TokenResponse {
            accessToken: ::std::option::Option::None,
            refreshToken: ::std::option::Option::None,
            error: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TokenResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TokenResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TokenResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TokenResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:illbuy.users.pb.Errors)
pub enum Errors {
    // @@protoc_insertion_point(enum_value:illbuy.users.pb.Errors.WrongPassword)
    WrongPassword = 0,
    // @@protoc_insertion_point(enum_value:illbuy.users.pb.Errors.WrongToken)
    WrongToken = 1,
    // @@protoc_insertion_point(enum_value:illbuy.users.pb.Errors.ConstrainFailed)
    ConstrainFailed = 2,
}

impl ::protobuf::Enum for Errors {
    const NAME: &'static str = "Errors";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<Errors> {
        match value {
            0 => ::std::option::Option::Some(Errors::WrongPassword),
            1 => ::std::option::Option::Some(Errors::WrongToken),
            2 => ::std::option::Option::Some(Errors::ConstrainFailed),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<Errors> {
        match str {
            "WrongPassword" => ::std::option::Option::Some(Errors::WrongPassword),
            "WrongToken" => ::std::option::Option::Some(Errors::WrongToken),
            "ConstrainFailed" => ::std::option::Option::Some(Errors::ConstrainFailed),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [Errors] = &[
        Errors::WrongPassword,
        Errors::WrongToken,
        Errors::ConstrainFailed,
    ];
}

impl ::protobuf::EnumFull for Errors {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("Errors").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for Errors {
    fn default() -> Self {
        Errors::WrongPassword
    }
}

impl Errors {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<Errors>("Errors")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10users/user.proto\x12\x0fillbuy.users.pb\"?\n\x0bUserRequest\x12\
    \x14\n\x05email\x18\x01\x20\x01(\tR\x05email\x12\x1a\n\x08password\x18\
    \x02\x20\x01(\tR\x08password\"9\n\x13RefreshTokenRequest\x12\"\n\x0crefr\
    eshToken\x18\x01\x20\x01(\tR\x0crefreshToken\"\xbe\x01\n\rTokenResponse\
    \x12%\n\x0baccessToken\x18\x01\x20\x01(\tH\0R\x0baccessToken\x88\x01\x01\
    \x12'\n\x0crefreshToken\x18\x02\x20\x01(\tH\x01R\x0crefreshToken\x88\x01\
    \x01\x122\n\x05error\x18\x03\x20\x01(\x0e2\x17.illbuy.users.pb.ErrorsH\
    \x02R\x05error\x88\x01\x01B\x0e\n\x0c_accessTokenB\x0f\n\r_refreshTokenB\
    \x08\n\x06_error*@\n\x06Errors\x12\x11\n\rWrongPassword\x10\0\x12\x0e\n\
    \nWrongToken\x10\x01\x12\x13\n\x0fConstrainFailed\x10\x022\xaa\x01\n\x0b\
    UserService\x12E\n\x05Login\x12\x1c.illbuy.users.pb.UserRequest\x1a\x1e.\
    illbuy.users.pb.TokenResponse\x12T\n\x0cRefreshToken\x12$.illbuy.users.p\
    b.RefreshTokenRequest\x1a\x1e.illbuy.users.pb.TokenResponseJ\xf1\x05\n\
    \x06\x12\x04\0\0\x1c\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\x08\n\x01\x02\
    \x12\x03\x02\0\x18\n\n\n\x02\x05\0\x12\x04\x04\0\x08\x01\n\n\n\x03\x05\0\
    \x01\x12\x03\x04\x05\x0b\n\x0b\n\x04\x05\0\x02\0\x12\x03\x05\x02\x14\n\
    \x0c\n\x05\x05\0\x02\0\x01\x12\x03\x05\x02\x0f\n\x0c\n\x05\x05\0\x02\0\
    \x02\x12\x03\x05\x12\x13\n\x0b\n\x04\x05\0\x02\x01\x12\x03\x06\x02\x11\n\
    \x0c\n\x05\x05\0\x02\x01\x01\x12\x03\x06\x02\x0c\n\x0c\n\x05\x05\0\x02\
    \x01\x02\x12\x03\x06\x0f\x10\n\x0b\n\x04\x05\0\x02\x02\x12\x03\x07\x02\
    \x16\n\x0c\n\x05\x05\0\x02\x02\x01\x12\x03\x07\x02\x11\n\x0c\n\x05\x05\0\
    \x02\x02\x02\x12\x03\x07\x14\x15\n\n\n\x02\x04\0\x12\x04\n\0\r\x01\n\n\n\
    \x03\x04\0\x01\x12\x03\n\x08\x13\n\x0b\n\x04\x04\0\x02\0\x12\x03\x0b\x02\
    \x13\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\x0b\x02\x08\n\x0c\n\x05\x04\0\
    \x02\0\x01\x12\x03\x0b\t\x0e\n\x0c\n\x05\x04\0\x02\0\x03\x12\x03\x0b\x11\
    \x12\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x0c\x02\x16\n\x0c\n\x05\x04\0\x02\
    \x01\x05\x12\x03\x0c\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\x0c\t\
    \x11\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x0c\x14\x15\n\n\n\x02\x04\x01\
    \x12\x04\x0f\0\x11\x01\n\n\n\x03\x04\x01\x01\x12\x03\x0f\x08\x1b\n\x0b\n\
    \x04\x04\x01\x02\0\x12\x03\x10\x02\x1a\n\x0c\n\x05\x04\x01\x02\0\x05\x12\
    \x03\x10\x02\x08\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\x10\t\x15\n\x0c\n\
    \x05\x04\x01\x02\0\x03\x12\x03\x10\x18\x19\n\n\n\x02\x04\x02\x12\x04\x13\
    \0\x17\x01\n\n\n\x03\x04\x02\x01\x12\x03\x13\x08\x15\n\x0b\n\x04\x04\x02\
    \x02\0\x12\x03\x14\x02\"\n\x0c\n\x05\x04\x02\x02\0\x04\x12\x03\x14\x02\n\
    \n\x0c\n\x05\x04\x02\x02\0\x05\x12\x03\x14\x0b\x11\n\x0c\n\x05\x04\x02\
    \x02\0\x01\x12\x03\x14\x12\x1d\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03\x14\
    \x20!\n\x0b\n\x04\x04\x02\x02\x01\x12\x03\x15\x02#\n\x0c\n\x05\x04\x02\
    \x02\x01\x04\x12\x03\x15\x02\n\n\x0c\n\x05\x04\x02\x02\x01\x05\x12\x03\
    \x15\x0b\x11\n\x0c\n\x05\x04\x02\x02\x01\x01\x12\x03\x15\x12\x1e\n\x0c\n\
    \x05\x04\x02\x02\x01\x03\x12\x03\x15!\"\n\x0b\n\x04\x04\x02\x02\x02\x12\
    \x03\x16\x02\x1c\n\x0c\n\x05\x04\x02\x02\x02\x04\x12\x03\x16\x02\n\n\x0c\
    \n\x05\x04\x02\x02\x02\x06\x12\x03\x16\x0b\x11\n\x0c\n\x05\x04\x02\x02\
    \x02\x01\x12\x03\x16\x12\x17\n\x0c\n\x05\x04\x02\x02\x02\x03\x12\x03\x16\
    \x1a\x1b\n\n\n\x02\x06\0\x12\x04\x19\0\x1c\x01\n\n\n\x03\x06\0\x01\x12\
    \x03\x19\x08\x13\n\x0b\n\x04\x06\0\x02\0\x12\x03\x1a\x021\n\x0c\n\x05\
    \x06\0\x02\0\x01\x12\x03\x1a\x06\x0b\n\x0c\n\x05\x06\0\x02\0\x02\x12\x03\
    \x1a\x0c\x17\n\x0c\n\x05\x06\0\x02\0\x03\x12\x03\x1a\"/\n\x0b\n\x04\x06\
    \0\x02\x01\x12\x03\x1b\x02@\n\x0c\n\x05\x06\0\x02\x01\x01\x12\x03\x1b\
    \x06\x12\n\x0c\n\x05\x06\0\x02\x01\x02\x12\x03\x1b\x13&\n\x0c\n\x05\x06\
    \0\x02\x01\x03\x12\x03\x1b1>b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(3);
            messages.push(UserRequest::generated_message_descriptor_data());
            messages.push(RefreshTokenRequest::generated_message_descriptor_data());
            messages.push(TokenResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(Errors::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
